### ISSUE TITLE
Failed to render template '.rubocop.yml.erb'

### ISSUE THREAD

**Issue by timhughes** [puppetlabs/pdk-module-template#28]
This is happening on fedora with ruby 2.1.9 when installing from gem

```
╰▶ hughest@argon [0] $ gem install pdk
Fetching: colored-1.2.gem (100%)
Successfully installed colored-1.2
Fetching: cri-2.9.1.gem (100%)
Successfully installed cri-2.9.1
Fetching: childprocess-0.6.3.gem (100%)
Successfully installed childprocess-0.6.3
Fetching: tty-spinner-0.4.1.gem (100%)
Successfully installed tty-spinner-0.4.1
Fetching: wisper-1.6.1.gem (100%)
Successfully installed wisper-1.6.1
Fetching: tty-cursor-0.4.0.gem (100%)
Successfully installed tty-cursor-0.4.0
Fetching: tty-color-0.4.2.gem (100%)
Successfully installed tty-color-0.4.2
Fetching: equatable-0.5.0.gem (100%)
Successfully installed equatable-0.5.0
Fetching: pastel-0.7.1.gem (100%)
Successfully installed pastel-0.7.1
Fetching: necromancer-0.4.0.gem (100%)
Successfully installed necromancer-0.4.0
Fetching: tty-prompt-0.12.0.gem (100%)
Successfully installed tty-prompt-0.12.0
Fetching: tty-which-0.3.0.gem (100%)
Successfully installed tty-which-0.3.0
Fetching: pdk-0.6.0.gem (100%)
Successfully installed pdk-0.6.0
13 gems installed
```

```
╰▶ hughest@argon [0] $ pdk new module test --debug
pdk (INFO): Creating new module: test

We need to create a metadata.json file for this module, so we're going to ask you 8 quick questions.
If the question is not applicable to this module, just leave the answer blank.

[Q 1/8] What is your Puppet Forge username?
This will be used when uploading your module to the Forge. You can opt out of this at any time.
--> hughest

[Q 2/8] What version is this module?
Puppet uses Semantic Versioning (semver.org) to version modules.
--> 0.1.0

[Q 3/8] Who wrote this module?
The person who gets credit for creating the module. 
--> hughest

[Q 4/8] What license does this module code fall under?
This should be an identifier from https://spdk.org/licenses/. Common values are "Apache-2.0", "MIT", or "proprietary".
--> Apache-2.0

[Q 5/8] How would you describe this module in a single sentence?
To help other Puppet users understand what the module does.
--> 

[Q 6/8] Where is this modules's source code repository?
Usually a GitHub URL
--> 

[Q 7/8] Where can others go to learn more about this module?
A web site that offers full information about your module.
--> 

[Q 8/8] Where can others go to file issues about this module?
A web site with a public bug tracker for your module.
--> 

----------------------------------------
SUMMARY
----------------------------------------
{
  "name": "hughest-test",
  "version": "0.1.0",
  "author": "hughest",
  "summary": "",
  "license": "Apache-2.0",
  "source": "",
  "dependencies": [
    {
      "name": "puppetlabs-stdlib",
      "version_requirement": ">= 4.13.1 < 5.0.0"
    }
  ],
  "operatingsystem_support": [
    {
      "operatingsystem": "Debian",
      "operatingsystemrelease": [
        "8"
      ]
    },
    {
      "operatingsystem": "RedHat",
      "operatingsystemrelease": [
        "7.0"
      ]
    },
    {
      "operatingsystem": "Ubuntu",
      "operatingsystemrelease": [
        "16.04"
      ]
    },
    {
      "operatingsystem": "windows",
      "operatingsystemrelease": [
        "2012 R2"
      ]
    }
  ]
}
----------------------------------------

About to generate this module; continue? Yes
pdk (DEBUG): PDK package installation not found, trying 'git' from the system PATH instead
pdk (DEBUG): PDK package installation not found, trying 'git' from the system PATH instead
pdk (DEBUG): Executing 'git --git-dir /home/hughest/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/pdk-0.6.0/.git describe --all --long'
pdk (DEBUG): PDK package installation not found, trying 'git' from the system PATH instead
pdk (DEBUG): PDK package installation not found, trying 'git' from the system PATH instead
pdk (DEBUG): Executing 'git clone https://github.com/puppetlabs/pdk-module-template /tmp/pdk-module-template20170810-28824-1tdu1da'
pdk (DEBUG): Rendering 'spec/spec_helper.rb.erb'...
pdk (DEBUG): Rendering 'spec/default_facts.yml.erb'...
pdk (DEBUG): Rendering 'appveyor.yml.erb'...
pdk (DEBUG): Rendering 'Rakefile.erb'...
pdk (DEBUG): Rendering 'README.md.erb'...
pdk (DEBUG): Rendering 'Gemfile.erb'...
pdk (DEBUG): Rendering 'CHANGELOG.md.erb'...
pdk (DEBUG): Rendering '.yardopts.erb'...
pdk (DEBUG): Rendering '.travis.yml.erb'...
pdk (DEBUG): Rendering '.rubocop.yml.erb'...
pdk (FATAL): Failed to render template '.rubocop.yml.erb'
RuntimeError: no defaults for rubocop 0.33.0 available
pdk (DEBUG): RuntimeError: no defaults for rubocop 0.33.0 available
pdk (DEBUG): /tmp/pdk-module-template20170810-28824-1tdu1da/moduleroot/.rubocop.yml.erb:38:in `render_erb'
pdk (DEBUG): /home/hughest/.rbenv/versions/2.1.9/lib/ruby/2.1.0/erb.rb:850:in `eval'
pdk (DEBUG): /home/hughest/.rbenv/versions/2.1.9/lib/ruby/2.1.0/erb.rb:850:in `result'
pdk (DEBUG): /home/hughest/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/pdk-0.6.0/lib/pdk/template_file.rb:75:in `render_erb'
pdk (DEBUG): /home/hughest/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/pdk-0.6.0/lib/pdk/template_file.rb:41:in `render'
pdk (DEBUG): /home/hughest/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/pdk-0.6.0/lib/pdk/module/templatedir.rb:111:in `block in render'
pdk (DEBUG): /home/hughest/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/pdk-0.6.0/lib/pdk/module/templatedir.rb:106:in `each'
pdk (DEBUG): /home/hughest/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/pdk-0.6.0/lib/pdk/module/templatedir.rb:106:in `render'
pdk (DEBUG): /home/hughest/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/pdk-0.6.0/lib/pdk/generators/module.rb:48:in `block in invoke'
pdk (DEBUG): /home/hughest/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/pdk-0.6.0/lib/pdk/module/templatedir.rb:64:in `initialize'
pdk (DEBUG): /home/hughest/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/pdk-0.6.0/lib/pdk/generators/module.rb:47:in `new'
pdk (DEBUG): /home/hughest/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/pdk-0.6.0/lib/pdk/generators/module.rb:47:in `invoke'
pdk (DEBUG): /home/hughest/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/pdk-0.6.0/lib/pdk/cli/new/module.rb:38:in `block (2 levels) in <module:CLI>'
pdk (DEBUG): /home/hughest/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/cri-2.9.1/lib/cri/command.rb:319:in `call'
pdk (DEBUG): /home/hughest/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/cri-2.9.1/lib/cri/command.rb:319:in `run_this'
pdk (DEBUG): /home/hughest/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/cri-2.9.1/lib/cri/command.rb:264:in `run'
pdk (DEBUG): /home/hughest/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/cri-2.9.1/lib/cri/command.rb:282:in `run'
pdk (DEBUG): /home/hughest/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/cri-2.9.1/lib/cri/command.rb:282:in `run'
pdk (DEBUG): /home/hughest/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/pdk-0.6.0/lib/pdk/cli.rb:15:in `run'
pdk (DEBUG): /home/hughest/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/pdk-0.6.0/exe/pdk:6:in `<top (required)>'
pdk (DEBUG): /home/hughest/.rbenv/versions/2.1.9/bin/pdk:23:in `load'
pdk (DEBUG): /home/hughest/.rbenv/versions/2.1.9/bin/pdk:23:in `<main>'
```

**Comment by timhughes** [comment]
The fix is to update rubocop to latest


╰▶ hughest@argon [0] $ gem install rubocop
Fetching: rubocop-0.49.1.gem (100%)
Successfully installed rubocop-0.49.1
1 gem installed
