### ISSUE TITLE
Add support for rubocop 0.50.0

### ISSUE THREAD

**Issue by bramblek1** [puppetlabs/pdk-module-template#50]
Similar to - but not the same as #28 
Tried with pdk 1.2.0 and 1.1.0
After the module interview - generating the module template fails . I found issue #28 related to upgrading rubocop , tried this without result. The cached pdk-module-template.git repo installed in /opt/puppetlabs/pdk/share/cache   has a rubocop 0.49.1 defaults file , and nothing else.

```
> pdk (DEBUG): PDK package installation not found. Trying 'git' from the system PATH instead.
> pdk (DEBUG): PDK package installation not found. Trying 'git' from the system PATH instead.
> pdk (DEBUG): Executing 'git clone file:///opt/puppetlabs/pdk/share/cache/pdk-module-template.git /tmp/pdk-module-template20171017-15892-1yg116q'
> pdk (DEBUG): Execution of 'git clone file:///opt/puppetlabs/pdk/share/cache/pdk-module-template.git /tmp/pdk-module-template20171017-15892-1yg116q' complete (duration: 0.182606174s; exit code: 0)
> pdk (DEBUG): Rendering '.rubocop.yml.erb'...
> pdk (FATAL): Failed to render template '.rubocop.yml.erb'
> RuntimeError: no defaults for rubocop 0.50.0 available
> pdk (DEBUG): RuntimeError: no defaults for rubocop 0.50.0 available
> pdk (DEBUG): /tmp/pdk-module-template20171017-15892-1yg116q/moduleroot/.rubocop.yml.erb:38:in `render_erb'
> pdk (DEBUG): /usr/lib/ruby/2.3.0/erb.rb:864:in `eval'
> pdk (DEBUG): /usr/lib/ruby/2.3.0/erb.rb:864:in `result'
> pdk (DEBUG): /var/lib/gems/2.3.0/gems/pdk-1.2.0/lib/pdk/template_file.rb:75:in `render_erb'
> pdk (DEBUG): /var/lib/gems/2.3.0/gems/pdk-1.2.0/lib/pdk/template_file.rb:41:in `render'
> pdk (DEBUG): /var/lib/gems/2.3.0/gems/pdk-1.2.0/lib/pdk/module/templatedir.rb:115:in `block in render'
> pdk (DEBUG): /var/lib/gems/2.3.0/gems/pdk-1.2.0/lib/pdk/module/templatedir.rb:110:in `each'
> pdk (DEBUG): /var/lib/gems/2.3.0/gems/pdk-1.2.0/lib/pdk/module/templatedir.rb:110:in `render'
> pdk (DEBUG): /var/lib/gems/2.3.0/gems/pdk-1.2.0/lib/pdk/generators/module.rb:74:in `block in invoke'
> pdk (DEBUG): /var/lib/gems/2.3.0/gems/pdk-1.2.0/lib/pdk/module/templatedir.rb:68:in `initialize'
> pdk (DEBUG): /var/lib/gems/2.3.0/gems/pdk-1.2.0/lib/pdk/generators/module.rb:73:in `new'
> pdk (DEBUG): /var/lib/gems/2.3.0/gems/pdk-1.2.0/lib/pdk/generators/module.rb:73:in `invoke'
> pdk (DEBUG): /var/lib/gems/2.3.0/gems/pdk-1.2.0/lib/pdk/cli/new/module.rb:28:in `block (2 levels) in <module:CLI>'
> pdk (DEBUG): /var/lib/gems/2.3.0/gems/cri-2.9.1/lib/cri/command.rb:319:in `run_this'
> pdk (DEBUG): /var/lib/gems/2.3.0/gems/cri-2.9.1/lib/cri/command.rb:264:in `run'
> pdk (DEBUG): /var/lib/gems/2.3.0/gems/cri-2.9.1/lib/cri/command.rb:282:in `run'
> pdk (DEBUG): /var/lib/gems/2.3.0/gems/cri-2.9.1/lib/cri/command.rb:282:in `run'
> pdk (DEBUG): /var/lib/gems/2.3.0/gems/pdk-1.2.0/lib/pdk/cli.rb:17:in `run'
> pdk (DEBUG): /var/lib/gems/2.3.0/gems/pdk-1.2.0/exe/pdk:6:in `<top (required)>'
> pdk (DEBUG): /usr/local/bin/pdk:23:in `load'
> pdk (DEBUG): /usr/local/bin/pdk:23:in `<main>'
```

**Comment by DavidS** [comment]
With the effort and churn around new rubocop versions, we won't get around to updating rubocop any time soon. Please use the 0.49.1 version, or add your own defaults by using the (profile_builder.rb)[https://github.com/puppetlabs/pdk-templates/blob/master/rubocop/profile_builder.rb] script.

Please note that this repo is dormant, and new development happens in https://github.com/puppetlabs/pdk-templates
